f = open('Скв. .txt', 'w')
bore_nm = input('Электронный журнал скважины No ')
f.write('Электронный журнал скважины No ')
f.write(bore_nm)
f.write(' \n')
bore_date = input('Дата: ')
f.write('Дата: ')
f.write(bore_date)
f.write(' \n')
bore_abs = input('Абс.отм., м: ')
f.write('Абс.отм., м: ')
f.write(bore_abs)
f.write(' \n')
bore_depth = input('Глуб.скв., м: ')
f.write('Глуб.скв., м: ')
f.write(bore_depth)
f.write(' \n')
layer_roof = input('Кровля ИГЭ, м: ')
f.write('Кровля ИГЭ, м: ')
f.write(layer_roof)
f.write(' \n')
layer_descr = input('Описание ИГЭ: ')
f.write('Описание ИГЭ: ')
f.write(layer_descr)
f.write(' \n')
sample_type = input('Вид образца: ')
f.write('Вид образца: ')
f.write(sample_type)
f.write(' \n')
sample_depth = input('Глуб.образца, м: ')
f.write('Глуб.образца, м: ')
f.write(sample_depth)
f.write(' \n')
sample_plus = input('Ещё образец? д/н ')
while sample_plus == 'д':
	sample_type = input('Вид образца: ')
	f.write('Вид образца: ')
	f.write(sample_type)
	f.write(' \n')
	sample_depth = input('Глуб.образца, м: ')
	f.write('Глуб.образца, м: ')
	f.write(sample_depth)
	f.write(' \n')
	sample_plus = input('Ещё образец? д/н ')
layer_depth = input('Подошва ИГЭ, м: ')
f.write('Подошва ИГЭ, м: ')
f.write(layer_depth)
f.write(' \n')
while bore_depth != layer_depth:
	layer_roof = input('Кровля ИГЭ, м: ')
	f.write('Кровля ИГЭ, м: ')
	f.write(layer_roof)
	f.write(' \n')
	layer_descr = input('Описание ИГЭ: ')
	f.write('Описание ИГЭ: ')
	f.write(layer_descr)
	f.write(' \n')
	sample_type = input('Вид образца: ')
	f.write('Вид образца: ')
	f.write(sample_type)
	f.write(' \n')
	sample_depth = input('Глуб.образца, м: ')
	f.write('Глуб.образца, м: ')
	f.write(sample_depth)
	f.write(' \n')
	sample_plus = input('Ещё образец? д/н ')
	while sample_plus == 'д':
		sample_type = input('Вид образца: ')
		f.write('Вид образца: ')
		f.write(sample_type)
		f.write(' \n')
		sample_depth = input('Глуб.образца, м: ')
		f.write('Глуб.образца, м: ')
		f.write(sample_depth)
		f.write(' \n')
		sample_plus = input('Ещё образец? д/н ')
	layer_depth = input('Подошва ИГЭ, м: ')
	f.write('Подошва ИГЭ, м: ')
	f.write(layer_depth)
f.close()