-- MySQL Script generated by MySQL Workbench
-- Вс 22 янв 2023 18:17:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EngGeo2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EngGeo2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EngGeo2` ;
USE `EngGeo2` ;

-- -----------------------------------------------------
-- Table `EngGeo2`.`Объект`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`Объект` (
  `idОбъект` VARCHAR(10) NOT NULL,
  `ОбъектНазвание` VARCHAR(200) NULL,
  `ОбъектЛокация` VARCHAR(100) NULL,
  `ОбъДатаЗаказ` DATE NULL,
  `ОбъДатаПолНач` DATE NULL,
  `ОбъДатаПолКон` DATE NULL,
  `ОбъДатаЛабНач` DATE NULL,
  `ОбъДатаКамНач` DATE NULL,
  `ОбъДатаКамКон` DATE NULL,
  `ОбъДатаСдача` DATE NULL,
  PRIMARY KEY (`idОбъект`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`ПолевОпыт`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`ПолевОпыт` (
  `idПолевОпыт` VARCHAR(10) NOT NULL,
  `idОбъект` VARCHAR(10) NOT NULL,
  `idСкв` VARCHAR(10) NOT NULL,
  `ПолОпытДата` DATE NULL,
  `ПолОпытВид` VARCHAR(45) NULL,
  `ПолОпытГлуб` FLOAT NULL,
  PRIMARY KEY (`idПолевОпыт`),
  INDEX `fk_ПолевОпыт_Объект1_idx` (`idСкв` ASC) VISIBLE,
  CONSTRAINT `fk_ПолевОпыт_Объект1`
    FOREIGN KEY (`idСкв`)
    REFERENCES `EngGeo2`.`Объект` (`idОбъект`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`Скважина`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`Скважина` (
  `idСкв` VARCHAR(10) NOT NULL,
  `idОбъект` VARCHAR(10) NOT NULL,
  `idПолевОпыт` VARCHAR(10) NOT NULL,
  `СквДата` DATE NULL,
  `СквАбсОтм` FLOAT NULL,
  `СквГлуб` FLOAT NULL,
  PRIMARY KEY (`idСкв`),
  INDEX `fk_Скважина_Объект_idx` (`idОбъект` ASC) VISIBLE,
  INDEX `fk_Скважина_ПолевОпыт1_idx` (`idПолевОпыт` ASC) VISIBLE,
  CONSTRAINT `fk_Скважина_Объект`
    FOREIGN KEY (`idОбъект`)
    REFERENCES `EngGeo2`.`Объект` (`idОбъект`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Скважина_ПолевОпыт1`
    FOREIGN KEY (`idПолевОпыт`)
    REFERENCES `EngGeo2`.`ПолевОпыт` (`idПолевОпыт`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`Слой`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`Слой` (
  `idСлой` VARCHAR(10) NOT NULL,
  `idОбъект` VARCHAR(10) NOT NULL,
  `СлойОписание` VARCHAR(200) NULL,
  PRIMARY KEY (`idСлой`),
  INDEX `fk_Слой_Объект1_idx` (`idОбъект` ASC) VISIBLE,
  CONSTRAINT `fk_Слой_Объект1`
    FOREIGN KEY (`idОбъект`)
    REFERENCES `EngGeo2`.`Объект` (`idОбъект`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`СлойСкв`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`СлойСкв` (
  `idСлойСкв` VARCHAR(45) NOT NULL,
  `idСкв` VARCHAR(10) NOT NULL,
  `idСлой` VARCHAR(10) NOT NULL,
  `СлойОписание` VARCHAR(200) NULL,
  `СлойКровля` FLOAT NULL,
  `СлойПодошва` FLOAT NULL,
  INDEX `fk_table1_Скважина1_idx` (`idСкв` ASC) VISIBLE,
  INDEX `fk_СлойСкв_Слой1_idx` (`idСлой` ASC) VISIBLE,
  PRIMARY KEY (`idСлойСкв`),
  CONSTRAINT `fk_table1_Скважина1`
    FOREIGN KEY (`idСкв`)
    REFERENCES `EngGeo2`.`Скважина` (`idСкв`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_СлойСкв_Слой1`
    FOREIGN KEY (`idСлой`)
    REFERENCES `EngGeo2`.`Слой` (`idСлой`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`ОбразецГрунт`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`ОбразецГрунт` (
  `NОбразГрунт` INT NOT NULL,
  `СлойСкв` VARCHAR(45) NOT NULL,
  `idСлой` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`NОбразГрунт`),
  INDEX `fk_ОбразецГрунт_СлойСкв1_idx` (`СлойСкв` ASC) VISIBLE,
  INDEX `fk_ОбразецГрунт_Слой1_idx` (`idСлой` ASC) VISIBLE,
  CONSTRAINT `fk_ОбразецГрунт_СлойСкв1`
    FOREIGN KEY (`СлойСкв`)
    REFERENCES `EngGeo2`.`СлойСкв` (`idСлойСкв`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ОбразецГрунт_Слой1`
    FOREIGN KEY (`idСлой`)
    REFERENCES `EngGeo2`.`Слой` (`idСлой`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`Вода`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`Вода` (
  `idВода` VARCHAR(100) NOT NULL,
  `idСкв` VARCHAR(10) NOT NULL,
  `УровеньГрВод` FLOAT NULL,
  `idОбъект` VARCHAR(10) NULL,
  PRIMARY KEY (`idВода`),
  INDEX `fk_Вода_Скважина1_idx` (`idСкв` ASC) VISIBLE,
  INDEX `fk_Вода_Объект1_idx` (`idОбъект` ASC) VISIBLE,
  CONSTRAINT `fk_Вода_Скважина1`
    FOREIGN KEY (`idСкв`)
    REFERENCES `EngGeo2`.`Скважина` (`idСкв`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Вода_Объект1`
    FOREIGN KEY (`idОбъект`)
    REFERENCES `EngGeo2`.`Объект` (`idОбъект`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`ВодаСкв`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`ВодаСкв` (
  `idВодаСкв` VARCHAR(100) NOT NULL,
  `idВода` VARCHAR(100) NOT NULL,
  `idСкв` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idВодаСкв`),
  INDEX `fk_ВодаСкв_Вода1_idx` (`idВода` ASC) VISIBLE,
  INDEX `fk_ВодаСкв_Скважина1_idx` (`idСкв` ASC) VISIBLE,
  CONSTRAINT `fk_ВодаСкв_Вода1`
    FOREIGN KEY (`idВода`)
    REFERENCES `EngGeo2`.`Вода` (`idВода`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ВодаСкв_Скважина1`
    FOREIGN KEY (`idСкв`)
    REFERENCES `EngGeo2`.`Скважина` (`idСкв`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`ОбразецВод`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`ОбразецВод` (
  `ОбразецВодcol` INT NOT NULL,
  `idОбразВод` VARCHAR(100) NOT NULL,
  `idВода` VARCHAR(100) NOT NULL,
  `ОбразВодКорр` VARCHAR(200) NULL,
  `ОбразецВодcol1`  NULL,
  PRIMARY KEY (`ОбразецВодcol`),
  INDEX `fk_ОбразецВод_ВодаСкв1_idx` (`idОбразВод` ASC) VISIBLE,
  INDEX `fk_ОбразецВод_Вода1_idx` (`idВода` ASC) VISIBLE,
  CONSTRAINT `fk_ОбразецВод_ВодаСкв1`
    FOREIGN KEY (`idОбразВод`)
    REFERENCES `EngGeo2`.`ВодаСкв` (`idВодаСкв`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ОбразецВод_Вода1`
    FOREIGN KEY (`idВода`)
    REFERENCES `EngGeo2`.`Вода` (`idВода`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EngGeo2`.`ОбразецКорр`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EngGeo2`.`ОбразецКорр` (
  `idОбразКорр` INT NOT NULL,
  `idСкв` VARCHAR(10) NOT NULL,
  `idОбъект` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idОбразКорр`),
  INDEX `fk_Коррозионность_Скважина1_idx` (`idСкв` ASC) VISIBLE,
  INDEX `fk_ОбразецКорр_Объект1_idx` (`idОбъект` ASC) VISIBLE,
  CONSTRAINT `fk_Коррозионность_Скважина1`
    FOREIGN KEY (`idСкв`)
    REFERENCES `EngGeo2`.`Скважина` (`idСкв`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ОбразецКорр_Объект1`
    FOREIGN KEY (`idОбъект`)
    REFERENCES `EngGeo2`.`Объект` (`idОбъект`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
